"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe) rather than True — a missing/misspelled
# env var in a new deployment should fail closed, not silently leak
# stack traces and settings to every visitor. Local dev sets this
# explicitly via backend/.env.example.
DEBUG = env.bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# No insecure fallback when DEBUG is off — a production deploy that
# forgets to set this should crash at startup, not silently run on a
# well-known, guessable key. The insecure default only exists to keep
# local `manage.py runserver` working out of the box.
SECRET_KEY = env("SECRET_KEY", default="") or ("django-insecure-development-only" if DEBUG else "")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable must be set when DEBUG is False."
    )

# Stripped per-entry: some hosting dashboards' env var editors are
# textareas, where a stray trailing newline or space from typing/
# pasting silently breaks Django's exact-match ALLOWED_HOSTS check.
ALLOWED_HOSTS = [
    host.strip()
    for host in env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
    if host.strip()
]

# Where the React app is served from — used to build Stripe Checkout's
# success/cancel redirect URLs.
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")

# Render (and the local nginx proxy, in prod-like compose) terminate
# TLS and forward plain HTTP to this container, setting this header
# to say the original request was HTTPS. Without it Django thinks
# every request is insecure, which would make the Secure cookie
# flags below silently drop the Django-admin session/CSRF cookies.
# No SECURE_SSL_REDIRECT here deliberately — Render already redirects
# HTTP to HTTPS at its edge, and adding a second redirect in Django
# risks a loop if this header is ever absent (e.g. a health check
# hitting the container directly).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'tenants',
    'academics',
    'attendance',
    'payments',
    'audit',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenants.middleware.TenantContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT'),
        # 'prefer' works unchanged against a local Postgres with no SSL
        # configured at all; hosted providers (e.g. Neon) that require
        # SSL set this to 'require' via POSTGRES_SSLMODE instead.
        'OPTIONS': {'sslmode': env('POSTGRES_SSLMODE', default='prefer')},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# See accounts/hashers.py for why the iteration count is tuned down from
# Django's default — it's the difference between login working and
# timing out entirely on a small shared-CPU instance.
PASSWORD_HASHERS = [
    "accounts.hashers.TunedPBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    # "login" and "payment-initiate" are applied explicitly via
    # ScopedRateThrottle on the views that need a tighter ceiling
    # than the general anon/user rates (brute-force login attempts,
    # repeated Stripe Checkout session creation).
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "180/min",
        "login": "8/min",
        "payment-initiate": "10/min",
    },
}
