# Generated by Django 5.2.13 on 2026-09-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_student_parents_parentstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentStudent',
        ),
    ]
