# Generated by Django 5.2.13 on 2026-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_feeinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('JAZZCASH', 'JazzCash')], max_length=20),
        ),
    ]
