# Generated by Django 5.2.13 on 2026-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttransaction_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_response_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_response_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='retrieval_reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
