# Generated by Django 5.2.17 on 2026-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'Stripe')], max_length=20),
        ),
    ]
